steps:
- name: 'hashicorp/terraform:1.0.0'
  id: 'Init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "GitHub Branch: $BRANCH_NAME"
      echo "Terraform Initialization"
      terraform init

- name: 'hashicorp/terraform:1.0.0'
  id: 'Build'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "Terraform Plan"
      terraform plan

- name: 'hashicorp/terraform:1.0.0'
  id: 'Code Quality'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "Terraform format and Validate"
      terraform fmt && terraform validate

- name: 'hashicorp/terraform:1.0.0'
  id: 'Destroy'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "Terraform Destroy"
      terraform destroy -auto-approve