# The image used in the cloud build steps is the official terraform image released by HashiCorp, Inc. over Dokcer Hub Registry.

steps:
- name: 'hashicorp/terraform:1.3.6'
  id: 'Init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*** Branch Name: $BRANCH_NAME ***"
      echo "*** Terraform Initialization ***"
      cd terraform
      terraform init

- name: 'hashicorp/terraform:1.3.6'
  id: 'Build'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*** Terraform Plan ***"
      cd terraform
      terraform plan

- name: 'hashicorp/terraform:1.3.6'
  id: 'Code Quality'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*** Terraform format and Validate ***"
      cd terraform
      terraform fmt && terraform validate

- name: 'hashicorp/terraform:1.3.6'
  id: 'Apply'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*** Terraform Apply ***"
      cd terraform
      terraform apply -auto-approve

logsBucket: 'gs://mgcp-tf-cloudbuild-logs'
options:
  logging: GCS_ONLY